### PR TITLE
Security Issue: signature is not checked

### PR DESCRIPTION
**Pull request by Alkorin**
Check signature if cert is NON-nil

### CODE REVIEW

**Comment by koesie10** [comment]
Thank you! The tests were using the wrong public key, which is why they failed, but that has also been fixed now.

**Comment by Alkorin** [comment]
You should maybe add some other tests like:
 - cert == nil
 - cert with wrong public key

To be sure that your library doesn't say "OK" even if it's the wrong public
key

Thomas

Le lun. 12 nov. 2018 à 12:35, Koen Vlaswinkel <notifications@github.com> a
écrit :

**Comment by koesie10** [comment]
Totally agree. However, the format of keys is binary, which makes it hard to construct valid or invalid responses. I also don't think there is some test suite which includes a list of valid/invalid responses.

**Comment by Alkorin** [comment]
I will definitely do some test suite because the library will be used for
$WORK internal authentication.

I'll share with you if I have some valid & invalid responses ;)

Thomas

Le ven. 16 nov. 2018 à 21:52, Koen Vlaswinkel <notifications@github.com> a
écrit :

**Pull request merged**
